# Generated by Django 4.0 on 2022-01-17 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredientCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('ingredient_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_category_id', to='ingredientCategory.ingredientcategory')),
            ],
        ),
    ]
