# Generated by Django 4.0 on 2022-01-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopList', '0001_initial'),
        ('recipe', '0004_lasttimecooked_alter_recipe_notes_and_more'),
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_id_ingredientRecipe', to='recipe.recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientShopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('shopList_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoplist_id_ingredientShopList', to='shopList.shoplist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
