# Generated by Django 4.0 on 2022-01-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_category_id',
            new_name='ingredient_category',
        ),
    ]
