# Generated by Django 4.0 on 2022-01-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_rename_ingredient_category_id_ingredient_ingredient_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredient',
            table='ingredient',
        ),
    ]
