# Generated by Django 4.0 on 2022-01-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_ingredientrecipe_ingredientshoplist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredientshoplist',
            name='shopList_id',
        ),
        migrations.DeleteModel(
            name='IngredientRecipe',
        ),
        migrations.DeleteModel(
            name='IngredientShopList',
        ),
    ]
