# Generated by Django 4.0 on 2022-01-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientShopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_shop_lists', to='ingredient.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(blank=True, null=True)),
                ('ingredient', models.ManyToManyField(related_name='shop_lists', through='shopList.IngredientShopList', to='ingredient.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientshoplist',
            name='shopList_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_list_ingredients', to='shopList.shoplist'),
        ),
    ]
