# Generated by Django 4.0 on 2022-01-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientshoplist',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='ingredientshoplist',
            old_name='shopList_id',
            new_name='shopList',
        ),
    ]
