# Generated by Django 4.0 on 2022-01-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopList', '0002_rename_ingredient_id_ingredientshoplist_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shoplist',
            table='shoplist',
        ),
    ]
