# Generated by Django 4.0 on 2022-01-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopList', '0003_alter_shoplist_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredientshoplist',
            table='ingredient_shoplist',
        ),
    ]
