branch-defaults:
  main:
    environment: smartcook-staging
    group_suffix: null
global:
  application_name: api-staging
  branch: null
  default_ec2_keyname: root-user-kp
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: smartcook_root
  repository: null
  sc: git
  workspace_type: Application
