# Generated by Django 4.0 on 2022-01-12 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
