# Generated by Django 4.0 on 2022-01-17 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesCreatedByUsers', '0001_initial'),
        ('recipe', '0003_lasttimecooked_recipenotes_recipe_difficulty_and_more'),
        ('user', '0002_user_follows_user_user_liked_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesInUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_names', to='categoriesCreatedByUsers.categoriescreatedbyusers')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_that_belongs_to_user_category', to='recipe.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_categories',
            field=models.ManyToManyField(related_name='profile_categories', through='user.CategoriesInUserProfile', to='recipe.Recipe'),
        ),
        migrations.AddField(
            model_name='categoriesinuserprofile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_that_owns_category', to='user.user'),
        ),
    ]
