# Generated by Django 4.0 on 2022-01-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_lasttimecooked_recipenotes_recipe_difficulty_and_more'),
        ('user', '0003_categoriesinuserprofile_user_profile_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_categories',
        ),
        migrations.AddField(
            model_name='user',
            name='user_profile_categories',
            field=models.ManyToManyField(related_name='user_profile_categories', through='user.CategoriesInUserProfile', to='recipe.Recipe'),
        ),
    ]
