# Generated by Django 4.0 on 2022-01-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_profile_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriesinuserprofile',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='categoriesinuserprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
