# Generated by Django 4.0 on 2022-01-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoriesinuserprofile',
            table='categories_in_user_profile',
        ),
    ]
