# Generated by Django 4.0 on 2022-01-17 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0003_lasttimecooked_recipenotes_recipe_difficulty_and_more'),
        ('user', '0004_remove_user_profile_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('breakfast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast', to='recipe.recipe')),
                ('dinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner', to='recipe.recipe')),
                ('lunch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch', to='recipe.recipe')),
                ('snack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snack', to='recipe.recipe')),
                ('tetime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tetime', to='recipe.recipe')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='user.user')),
            ],
        ),
    ]
