# Generated by Django 4.0 on 2022-01-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('breakfast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast', to='recipe.recipe')),
                ('dinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner', to='recipe.recipe')),
                ('lunch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch', to='recipe.recipe')),
                ('snack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snack', to='recipe.recipe')),
                ('tetime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tetime', to='recipe.recipe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user')),
            ],
        ),
    ]
