# Generated by Django 4.0 on 2022-01-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyMenus', '0002_rename_user_id_dailymenus_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailymenus',
            table='daily_menus',
        ),
    ]
