# Generated by Django 4.0 on 2022-01-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.PositiveIntegerField()),
                ('tips', models.TextField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('calories', models.FloatField()),
                ('fat', models.FloatField()),
                ('proteins', models.FloatField()),
                ('carbs', models.FloatField()),
                ('portions', models.PositiveIntegerField()),
            ],
        ),
    ]
