# Generated by Django 4.0 on 2022-01-17 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_follows_user_user_liked_recipes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastTimeCooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastTimeCooked', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='lastTimeCooked',
            field=models.ManyToManyField(related_name='last_time_cooked_recipes', through='recipe.LastTimeCooked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.ManyToManyField(related_name='recipes_notes', through='recipe.RecipeNotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipenotes',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_recipe_notes', to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='recipenotes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recipe_notes', to='user.user'),
        ),
        migrations.AddField(
            model_name='lasttimecooked',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_last_time_cooked', to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='lasttimecooked',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_last_time_cooked', to='user.user'),
        ),
    ]
