# Generated by Django 4.0 on 2022-01-12 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_user_liked_recipes'),
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.ManyToManyField(through='recipe.RecipeNotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipenotes',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_id_recipeNotes', to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='recipenotes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_recipeNotes', to='user.user'),
        ),
    ]
