# Generated by Django 4.0 on 2022-01-12 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_user_liked_recipes'),
        ('recipe', '0003_recipenotes_recipe_notes_recipenotes_recipe_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastTimeCooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastTimeCooked', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.ManyToManyField(through='recipe.LastTimeCooked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lasttimecooked',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_id_lastTimeCooked', to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='lasttimecooked',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_lastTimeCooked', to='user.user'),
        ),
    ]
