# Generated by Django 4.0 on 2022-01-19 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_remove_user_profile_categories_and_more'),
        ('recipe', '0004_ingredientrecipe_recipe_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lasttimecooked',
            name='lastTimeCooked',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='lastTimeCooked',
        ),
        migrations.AddField(
            model_name='lasttimecooked',
            name='lastDateCooked',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='lastDateCooked',
            field=models.ManyToManyField(related_name='last_date_cooked_recipes', through='recipe.LastTimeCooked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lasttimecooked',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_last_date_cooked', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='lasttimecooked',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_last_date_cooked', to='user.user'),
        ),
    ]
