# Generated by Django 4.0 on 2022-01-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipe_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredientrecipe',
            table='ingredient_recipe',
        ),
        migrations.AlterModelTable(
            name='lasttimecooked',
            table='last_time_cooked',
        ),
        migrations.AlterModelTable(
            name='recipenotes',
            table='recipe_notes',
        ),
    ]
