# Generated by Django 4.0 on 2022-01-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_remove_lasttimecooked_lasttimecooked_and_more'),
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='name',
        ),
        migrations.RemoveField(
            model_name='step',
            name='recipe_id',
        ),
        migrations.AddField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_step', to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='step',
            name='step_number',
            field=models.IntegerField(default=None),
        ),
    ]
