# Generated by Django 4.0 on 2022-01-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_remove_step_name_remove_step_recipe_id_step_recipe_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='step',
            table='step',
        ),
    ]
