# Generated by Django 4.0 on 2022-01-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientCategory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredientcategory',
            table='ingredient_category',
        ),
    ]
