# Generated by Django 4.0 on 2022-01-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0003_lasttimecooked_recipenotes_recipe_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('dish_category_intermediate', models.ManyToManyField(related_name='dish_categories', to='recipe.Recipe')),
            ],
        ),
    ]
