# Generated by Django 4.0 on 2022-01-12 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('recipe_id_dishCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_id_dishCategory', to='recipe.recipe')),
            ],
        ),
    ]
