# Generated by Django 4.0 on 2022-01-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesCreatedByUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoriescreatedbyusers',
            table='categories_created_by_users',
        ),
    ]
